// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/focus_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3451917468651974437),
    name: 'FocusCycleEntity',
    lastPropertyId: const obx_int.IdUid(11, 8429210591341086170),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8554200977599456232),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6435539505586157054),
        name: 'fcId',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(1, 4634393037725044947),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3744446576263336024),
        name: 'date',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 5450463407323132214),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5299956825105043470),
        name: 'startTime',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7597449861763875472),
        name: 'endTime',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1244035276527092906),
        name: 'subject',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 365411555975028098),
        name: 'studyMin',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 9096905199144426927),
        name: 'lectureMin',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3615135766235628664),
        name: 'effectiveMin',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4904074207050006839),
        name: 'restMin',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8429210591341086170),
        name: 'segmentsJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 3451917468651974437),
    lastIndexId: const obx_int.IdUid(2, 5450463407323132214),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FocusCycleEntity: obx_int.EntityDefinition<FocusCycleEntity>(
      model: _entities[0],
      toOneRelations: (FocusCycleEntity object) => [],
      toManyRelations: (FocusCycleEntity object) => {},
      getId: (FocusCycleEntity object) => object.obxId,
      setId: (FocusCycleEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (FocusCycleEntity object, fb.Builder fbb) {
        final fcIdOffset = fbb.writeString(object.fcId);
        final dateOffset = fbb.writeString(object.date);
        final startTimeOffset = fbb.writeString(object.startTime);
        final endTimeOffset = object.endTime == null
            ? null
            : fbb.writeString(object.endTime!);
        final subjectOffset = fbb.writeString(object.subject);
        final segmentsJsonOffset = fbb.writeString(object.segmentsJson);
        fbb.startTable(12);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, fcIdOffset);
        fbb.addOffset(2, dateOffset);
        fbb.addOffset(3, startTimeOffset);
        fbb.addOffset(4, endTimeOffset);
        fbb.addOffset(5, subjectOffset);
        fbb.addInt64(6, object.studyMin);
        fbb.addInt64(7, object.lectureMin);
        fbb.addInt64(8, object.effectiveMin);
        fbb.addInt64(9, object.restMin);
        fbb.addOffset(10, segmentsJsonOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final fcIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final dateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final startTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final endTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final subjectParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final studyMinParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final lectureMinParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final effectiveMinParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final restMinParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final segmentsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final object = FocusCycleEntity(
          obxId: obxIdParam,
          fcId: fcIdParam,
          date: dateParam,
          startTime: startTimeParam,
          endTime: endTimeParam,
          subject: subjectParam,
          studyMin: studyMinParam,
          lectureMin: lectureMinParam,
          effectiveMin: effectiveMinParam,
          restMin: restMinParam,
          segmentsJson: segmentsJsonParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FocusCycleEntity] entity fields to define ObjectBox queries.
class FocusCycleEntity_ {
  /// See [FocusCycleEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<FocusCycleEntity>(
    _entities[0].properties[0],
  );

  /// See [FocusCycleEntity.fcId].
  static final fcId = obx.QueryStringProperty<FocusCycleEntity>(
    _entities[0].properties[1],
  );

  /// See [FocusCycleEntity.date].
  static final date = obx.QueryStringProperty<FocusCycleEntity>(
    _entities[0].properties[2],
  );

  /// See [FocusCycleEntity.startTime].
  static final startTime = obx.QueryStringProperty<FocusCycleEntity>(
    _entities[0].properties[3],
  );

  /// See [FocusCycleEntity.endTime].
  static final endTime = obx.QueryStringProperty<FocusCycleEntity>(
    _entities[0].properties[4],
  );

  /// See [FocusCycleEntity.subject].
  static final subject = obx.QueryStringProperty<FocusCycleEntity>(
    _entities[0].properties[5],
  );

  /// See [FocusCycleEntity.studyMin].
  static final studyMin = obx.QueryIntegerProperty<FocusCycleEntity>(
    _entities[0].properties[6],
  );

  /// See [FocusCycleEntity.lectureMin].
  static final lectureMin = obx.QueryIntegerProperty<FocusCycleEntity>(
    _entities[0].properties[7],
  );

  /// See [FocusCycleEntity.effectiveMin].
  static final effectiveMin = obx.QueryIntegerProperty<FocusCycleEntity>(
    _entities[0].properties[8],
  );

  /// See [FocusCycleEntity.restMin].
  static final restMin = obx.QueryIntegerProperty<FocusCycleEntity>(
    _entities[0].properties[9],
  );

  /// See [FocusCycleEntity.segmentsJson].
  static final segmentsJson = obx.QueryStringProperty<FocusCycleEntity>(
    _entities[0].properties[10],
  );
}
